version: '3'

services:
  stratocumulus:
    build: ./
    command: gunicorn stratocumulus:app --worker-class gevent --reload --bind 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/app
    environment:
      STRATO_SECRET_KEY: bananarama
      STRATO_STATIC_FOLDER: /usr/src/static
    depends_on:
      - redis
      - stratocumulus_client
    links:
      - redis:redis
    ports:
      - 80:8000

  stratocumulus_celery:
    build: ./
    command: celery -A stratocumulus.client worker --loglevel=info
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/static
    environment:
      STRATO_SECRET_KEY: bananarama
      STRATO_STATIC_FOLDER: /usr/src/static
    depends_on:
      - redis
      - stratocumulus
    links:
      - redis:redis
      - stratocumulus:stratocumulus

  stratocumulus_client:
    build: ./client/
    command: npx webpack --watch

  redis:
    image: redis:latest
