version: '3'

services:
  stratocumulus:
    build: ./server/
    command: gunicorn stratocumulus:app --log-level=info --worker-class gevent --reload --bind 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/static
    environment:
      STRATO_PLUGIN: arc # arc, lincs
      STRATO_SECRET_KEY: bananarama
      STRATO_STATIC_FOLDER: /usr/src/static
      STRATO_CORPORA_HOST: https://example.org # your Corpora API endpoint
      STRATO_CORPORA_CORPUS_ID: 123456789abcdef # your Corpora corpus ID
    depends_on:
      - redis
      - stratocumulus_client
    links:
      - redis:redis
    ports:
      - 80:8000

  stratocumulus_celery:
    build: ./server/
    command: celery -A stratocumulus.client worker --loglevel=info
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/static
    environment:
      STRATO_PLUGIN: arc # arc, lincs
      STRATO_SECRET_KEY: bananarama
      STRATO_STATIC_FOLDER: /usr/src/static
      STRATO_CORPORA_HOST: https://example.org # your Corpora API endpoint
      STRATO_CORPORA_CORPUS_ID: 123456789abcdef # your Corpora corpus ID
    depends_on:
      - redis
      - stratocumulus
    links:
      - redis:redis
      - stratocumulus:stratocumulus

  stratocumulus_client:
    build: ./client/
    volumes:
      - ./client/lib:/usr/src/client/lib
      - static:/usr/src/client/dist

  redis:
    image: redis:latest

volumes:
  static:
