version: '3'

services:
  stratocumulus:
    build: ./server/
    command: gunicorn stratocumulus:app --log-level=info --worker-class gevent --reload --bind 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/static
    environment:
      STRATO_SECRET_KEY: bananarama
      STRATO_STATIC_FOLDER: /usr/src/static
      # PRODUCTION CORPORA
      STRATO_CORPORA_HOST: https://corpora.dh.tamu.edu
      STRATO_CORPORA_CORPUS_ID: 5f623b8eff276600a4f44553
      # LOCAL CORPORA
      # STRATO_CORPORA_HOST: http://host.docker.internal
      # STRATO_CORPORA_CORPUS_ID: 6398f4be0751727e7d1db3f7
      # DEV CORPORA
      # STRATO_CORPORA_HOST: https://corpora-dev.dh.tamu.edu
      # STRATO_CORPORA_CORPUS_ID: 5f623b8eff276600a4f44553
    depends_on:
      - redis
      - stratocumulus_client
    links:
      - redis:redis
    ports:
      - 80:8000

  stratocumulus_celery:
    build: ./server/
    command: celery -A stratocumulus.client worker --loglevel=info
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/static
    environment:
      STRATO_SECRET_KEY: bananarama
      STRATO_STATIC_FOLDER: /usr/src/static
      # PRODUCTION CORPORA
      STRATO_CORPORA_HOST: https://corpora.dh.tamu.edu
      STRATO_CORPORA_CORPUS_ID: 5f623b8eff276600a4f44553
      # LOCAL CORPORA
      # STRATO_CORPORA_HOST: http://host.docker.internal
      # STRATO_CORPORA_CORPUS_ID: 6398f4be0751727e7d1db3f7
      # DEV CORPORA
      # STRATO_CORPORA_HOST: https://corpora-dev.dh.tamu.edu
      # STRATO_CORPORA_CORPUS_ID: 5f623b8eff276600a4f44553
    depends_on:
      - redis
      - stratocumulus
    links:
      - redis:redis
      - stratocumulus:stratocumulus

  stratocumulus_client:
    build: ./client/
    volumes:
      - ./client/lib:/usr/src/client/lib
      - static:/usr/src/client/dist

  redis:
    image: redis:latest

volumes:
  static:
